---
Name: silverware-datepicker
---

# Configure Admin Requirements:

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - silverware/datepicker:client/dist/styles/bundle.css
  extra_requirements_javascript:
    - silverware/datepicker:client/dist/js/bundle.js

# Configure Date Field:

SilverStripe\Forms\DateField:
  extensions:
    - SilverWare\Datepicker\Extensions\DateFieldExtension
  default_datepicker_format: d MMM yyyy
  default_datepicker_polyfill: all
